Cobit-19/Models/AppDbContext.cs
This is an example of using a pull request to merge feature branch into develop
=> Test Commit

Cobit-19/Models/AppDbContext.cs
=> Given seeding data

Cobit-19/Business/FocusAreas/FocusAreaProvider.cs, Cobit-19/Shared/Profiles/UserEditorProfile.cs, Tests/FocusAreaProviderTests.cs
Added some initial methods for the focus area provider, also added some basic unit tests.
=> Added initial methods for the focus area provider.

Cobit-19/Business/Audits/AuditProvider.cs, Cobit-19/Business/Audits/MappingService.cs, Cobit-19/Pages/Audit.razor, Cobit-19/Pages/DesignFactor.razor, Cobit-19/Pages/Shared/NavMenu.razor, Cobit-19/Program.cs
- Started AuditHomePage
- Added Syncfusion licence using Secrets
- Cleanup of DesignFactor page
=> Design factor page

Cobit-19/Pages/AuditSelect.razor, Cobit-19/Pages/AuditSelectTable.razor, Cobit-19/Pages/FocusAreaSelectTable.razor, Cobit-19/Pages/UserHome.razor
-Styled elements within the user home page and audit select page a bit better, still needs a bit more work however styling wise.
-Added the static content displayed in the user home page.
-Linked up the audit selection page to the audit page.
=> Styled elements in user home and audit select a bit better.

Cobit-19/Data/AppDbContext.cs, Cobit-19/Migrations/20230725182919_SeededAllNecessaryRoles.Designer.cs, Cobit-19/Migrations/20230725182919_SeededAllNecessaryRoles.cs, Cobit-19/Pages/UserHome.razor
- Added seeding for the other roles needed for the solution.
- Made small styling fixes for the user home page.
=> Role creation

Cobit-19/Pages/_Host.cshtml
- Added authorization on start up. This way a user that is not logged in will first see the login page.
=> Fixed redirect for a user that is not logged in.

Cobit-19/Pages/Audit.razor, Cobit-19/Pages/AuditSelectTable.razor, Cobit-19/Pages/Shared/NavMenu.razor
Added Styling and the active badges
=> Added Styling, and the Inactive badges

Cobit-19/Business/Audits/AuditProvider.cs, Cobit-19/Pages/Audit/Audit.razor
Users can now only access audits that they are assigned to.
=> Added better authorization for audits

Cobit-19/Business/Reports/ReportProvider.cs, Cobit-19/Cobit-19.csproj, Cobit-19/Pages/Audit/Audit.razor, Cobit-19/Pages/Reporting/Reports.razor, Cobit-19/Pages/_Host.cshtml, Cobit-19/Program.cs, Cobit-19/Properties/launchSettings.json, Cobit-19/wwwroot/js/interop.js
- Added reports page
- Added Report Provider
- Added first basic version of Objective Audit Report.
=> Reporting daniel

Cobit-19/Business/Admin/UserManagementProvider.cs, Cobit-19/Business/Audits/AuditProvider.cs, Cobit-19/Business/FocusAreas/FocusAreaProvider.cs, Cobit-19/Data/AppDbContext.cs, Cobit-19/Data/Models/ApplicationUser.cs, Cobit-19/Migrations/20231026201936_Fixed-GovernaceAuditor-SeedingIssue.cs, Cobit-19/Pages/Administrator/UserManagement.razor, Cobit-19/Pages/Audit/ManageAudits.razor, Cobit-19/Pages/Shared/NavMenu.razor, Cobit-19/Shared/Dtos/UserEditorDto.cs
- Created user management page
- Able to create new users and delete users
- When an admin user is created, they are added to all audits
- Notifications are shown when the user is created or deleted in the top left of the screen
- Basic styling done on this page
- Manage Users option added, which is only shown for admin users on the Nav bar.
=> User management page.

Cobit-19/Business/ObjectiveAudits/ObjectiveAuditProvider.cs, Cobit-19/Data/AppDbContext.cs, Cobit-19/Migrations/20231027092510_ObjectiveAuditMemberSeeding.cs, Cobit-19/Pages/ObjectiveAudit/ObjectiveAuditSelect.razor
- Only objective audits someone is assigned to is now shown.
=> Audits only shown for selected members

Cobit-19/Business/ObjectiveAudits/ObjectiveAuditProvider.cs, Cobit-19/Pages/Audit/Audit.razor, Cobit-19/Pages/DesignFactor/DesignFactor.razor, Cobit-19/Pages/DesignFactor/DesignFactorReport.razor, Cobit-19/Pages/ObjectiveAudit/Component.razor, Cobit-19/Pages/ObjectiveAudit/ObjectiveAuditDashboard.razor, Cobit-19/Pages/ObjectiveAudit/ObjectiveAuditSelect.razor
Added Audit status panel 
Added back buttons
=> Fixes gerni

Cobit-19/Business/Admin/UserManagementProvider.cs, Cobit-19/Pages/Shared/NavMenu.razor
- Name, surname and role added to navbar
- Fixed some dbcontext simultaneous operations issues.
=> Name and role shown in nav menu.

Cobit-19/Business/Reports/GoalsCascadeReport.cs, Cobit-19/Business/Reports/ObjectiveAuditData.cs, Cobit-19/Business/Reports/ObjectiveAuditReport.cs, Cobit-19/Business/Reports/ReportProvider.cs, Cobit-19/Pages/DesignFactor/DesignFactor.razor, Cobit-19/Pages/ObjectiveAudit/ObjectiveAuditDashboard.razor, Cobit-19/Pages/ObjectiveAudit/ObjectiveAuditSelect.razor, Cobit-19/Pages/Reporting/Reports.razor
- Added V1 of objective audit Report
- Enhanced Goals cascade UI
=> Objective report

Cobit-19/Business/Audits/AuditProvider.cs, Cobit-19/Pages/ObjectiveAudit/QuestionTable.razor, Cobit-19/Properties/launchSettings.json
- All admin users can now view all newly created objective audits.
- Question comments are now saved to the database.
=> Objective audit bug fixes

Cobit-19/Business/Audits/AuditProvider.cs, Cobit-19/Data/AppDbContext.cs, Cobit-19/Pages/Administrator/UserManagement.razor, Cobit-19/Pages/Audit/Audit.razor, Cobit-19/Pages/DesignFactor/DesignFactor.razor, Cobit-19/Pages/ObjectiveAudit/ObjectiveAuditDashboard.razor, Cobit-19/Pages/ObjectiveAudit/ObjectiveAuditSelect.razor, Cobit-19/Pages/ObjectiveAudit/QuestionTable.razor
Removed Reports row in Audit Screen
Added Report Button in Objective Audit Dashboard
Checks if the Auditor is not assigned to Objective Audit
Added table to User Management Screen
Removed Audits 2 - 5 (Was seeded faulty)
Fixed User and Focus Area not being included in getAsync method 
Format of Objective table selections
Design factor Risk Rating
=> Bug fixes gerni

Cobit-19/Pages/ObjectiveAudit/ObjectiveAuditDashboard.razor, Cobit-19/Pages/ObjectiveAudit/ObjectiveAuditSelect.razor
- Full name of objective shown in objective audits.
=> Show full name of objective

Cobit-19/Areas/Identity/Pages/Account/Login.cshtml, Cobit-19/Areas/Identity/Pages/Account/Login.cshtml.cs, Cobit-19/Business/ObjectiveAudits/ObjectiveAuditProvider.cs, Cobit-19/Pages/Administrator/UserManagement.razor, Cobit-19/Pages/Audit/ManageAudits.razor, Cobit-19/Pages/ObjectiveAudit/ObjectiveAuditDashboard.razor, Cobit-19/Pages/Shared/MainLayout.razor, Cobit-19/Program.cs
- Logout works now, removed Assesment center redirect.
-  User and audit management page are now dynamic.
- The bug that popped up that threw an error when opening objective audits has been fixed.
=> bug fixes for final issue

Cobit-19/Pages/Audit/ManageAudits.razor, Cobit-19/Pages/ObjectiveAudit/ObjectiveAuditSelect.razor
- Auditor view (Removed the columns asked to be removed in Objective Audit Select)
- Added a back button in Manage Audits page.
=> Continued bug fixes.

Cobit-19/Business/Audits/AuditProvider.cs, Cobit-19/Data/AppDbContext.cs, Cobit-19/Migrations/20231112154104_Head-Auditor-Seeding.cs, Cobit-19/Pages/Audit/ManageAudits.razor, Cobit-19/Pages/ObjectiveAudit/Component.razor
- Back button in objective audits goes to the objective audit select page instead as per request.
- Head Auditor is now assigned to all objective audits when audit is created.
=> Added button, head auditor changes

Cobit-19/Areas/Identity/Pages/Account/Login.cshtml
Login Page browser tab renamed.
=> LoginPage_tab
